using Microsoft.EntityFrameworkCore;
using TripleTriadApi.Data;
using TripleTriadApi.Models;

namespace TripleTriadApi.Services
{
    public class CardSeederService
    {
        public static async Task SeedCardsAsync(TripleTriadContext context)
        {
            // Ensure database is created first
            await context.Database.EnsureCreatedAsync();

            if (await context.Cards.AnyAsync())
            {
                return; // Cards already seeded
            }
            var cards = new List<Card>
            {
                // Level 10 GF & Character Cards
                new()
                {
                    Id = 1,
                    Name = "Squall",
                    Image = "squall.jpg",
                    TopValue = 10,
                    RightValue = 4,
                    BottomValue = 6,
                    LeftValue = 9,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 2,
                    Name = "Rinoa",
                    Image = "rinoa.jpg",
                    TopValue = 4,
                    RightValue = 10,
                    BottomValue = 2,
                    LeftValue = 10,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 3,
                    Name = "Quistis",
                    Image = "quistis.jpg",
                    TopValue = 9,
                    RightValue = 6,
                    BottomValue = 10,
                    LeftValue = 2,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 4,
                    Name = "Zell",
                    Image = "zell.jpg",
                    TopValue = 8,
                    RightValue = 5,
                    BottomValue = 10,
                    LeftValue = 4,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 5,
                    Name = "Selphie",
                    Image = "selphie.jpg",
                    TopValue = 10,
                    RightValue = 8,
                    BottomValue = 6,
                    LeftValue = 4,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 6,
                    Name = "Irvine",
                    Image = "irvine.jpg",
                    TopValue = 2,
                    RightValue = 6,
                    BottomValue = 9,
                    LeftValue = 10,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 7,
                    Name = "Seifer",
                    Image = "seifer.jpg",
                    TopValue = 6,
                    RightValue = 9,
                    BottomValue = 10,
                    LeftValue = 4,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 8,
                    Name = "Edea",
                    Image = "edea.jpg",
                    TopValue = 10,
                    RightValue = 10,
                    BottomValue = 3,
                    LeftValue = 3,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 9,
                    Name = "Laguna",
                    Image = "laguna.jpg",
                    TopValue = 5,
                    RightValue = 10,
                    BottomValue = 3,
                    LeftValue = 9,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 10,
                    Name = "Kiros",
                    Image = "kiros.jpg",
                    TopValue = 6,
                    RightValue = 7,
                    BottomValue = 6,
                    LeftValue = 10,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 11,
                    Name = "Ward",
                    Image = "ward.jpg",
                    TopValue = 10,
                    RightValue = 7,
                    BottomValue = 8,
                    LeftValue = 2,
                    Element = "none",
                    Level = 10,
                },
                // Level 9 GF Cards
                new()
                {
                    Id = 18,
                    Name = "Odin",
                    Image = "odin.jpg",
                    TopValue = 8,
                    RightValue = 10,
                    BottomValue = 3,
                    LeftValue = 5,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 17,
                    Name = "Eden",
                    Image = "eden.jpg",
                    TopValue = 4,
                    RightValue = 4,
                    BottomValue = 9,
                    LeftValue = 10,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 16,
                    Name = "Doomtrain",
                    Image = "doomtrain.jpg",
                    TopValue = 3,
                    RightValue = 1,
                    BottomValue = 10,
                    LeftValue = 10,
                    Element = "poison",
                    Level = 10,
                },
                new()
                {
                    Id = 15,
                    Name = "Bahamut",
                    Image = "bahamut.jpg",
                    TopValue = 10,
                    RightValue = 8,
                    BottomValue = 2,
                    LeftValue = 6,
                    Element = "none",
                    Level = 10,
                },
                new()
                {
                    Id = 14,
                    Name = "Phoenix",
                    Image = "phoenix.jpg",
                    TopValue = 7,
                    RightValue = 2,
                    BottomValue = 7,
                    LeftValue = 10,
                    Element = "fire",
                    Level = 10,
                },
                new()
                {
                    Id = 19,
                    Name = "Carbuncle",
                    Image = "carbuncle.jpg",
                    TopValue = 8,
                    RightValue = 4,
                    BottomValue = 10,
                    LeftValue = 4,
                    Element = "none",
                    Level = 9,
                },
                new()
                {
                    Id = 20,
                    Name = "Leviathan",
                    Image = "leviathan.jpg",
                    TopValue = 7,
                    RightValue = 10,
                    BottomValue = 1,
                    LeftValue = 7,
                    Element = "water",
                    Level = 9,
                },
                new()
                {
                    Id = 21,
                    Name = "Pandemona",
                    Image = "pandemona.jpg",
                    TopValue = 10,
                    RightValue = 1,
                    BottomValue = 7,
                    LeftValue = 7,
                    Element = "wind",
                    Level = 9,
                },
                new()
                {
                    Id = 24,
                    Name = "Cerberus",
                    Image = "cerberus.jpg",
                    TopValue = 7,
                    RightValue = 4,
                    BottomValue = 6,
                    LeftValue = 10,
                    Element = "none",
                    Level = 9,
                },
                new()
                {
                    Id = 23,
                    Name = "Alexander",
                    Image = "alexander.jpg",
                    TopValue = 9,
                    RightValue = 10,
                    BottomValue = 4,
                    LeftValue = 2,
                    Element = "holy",
                    Level = 9,
                },
                new()
                {
                    Id = 30,
                    Name = "Diablos",
                    Image = "diablos.jpg",
                    TopValue = 5,
                    RightValue = 10,
                    BottomValue = 8,
                    LeftValue = 3,
                    Element = "none",
                    Level = 9,
                },
                // Level 8 Boss Cards
                new()
                {
                    Id = 29,
                    Name = "Minotaur",
                    Image = "minotaur.jpg",
                    TopValue = 9,
                    RightValue = 5,
                    BottomValue = 2,
                    LeftValue = 9,
                    Element = "earth",
                    Level = 9,
                },
                new()
                {
                    Id = 28,
                    Name = "Sacred",
                    Image = "sacred.jpg",
                    TopValue = 5,
                    RightValue = 1,
                    BottomValue = 9,
                    LeftValue = 9,
                    Element = "earth",
                    Level = 8,
                },
                new()
                {
                    Id = 27,
                    Name = "Siren",
                    Image = "siren.jpg",
                    TopValue = 8,
                    RightValue = 9,
                    BottomValue = 6,
                    LeftValue = 2,
                    Element = "none",
                    Level = 9,
                },
                new()
                {
                    Id = 26,
                    Name = "Ifrit",
                    Image = "ifrit.jpg",
                    TopValue = 9,
                    RightValue = 6,
                    BottomValue = 2,
                    LeftValue = 8,
                    Element = "fire",
                    Level = 9,
                },
                new()
                {
                    Id = 25,
                    Name = "Shiva",
                    Image = "shiva.jpg",
                    TopValue = 6,
                    RightValue = 7,
                    BottomValue = 4,
                    LeftValue = 9,
                    Element = "ice",
                    Level = 8,
                },
                new()
                {
                    Id = 22,
                    Name = "Quezacotl",
                    Image = "quezacotl.jpg",
                    TopValue = 2,
                    RightValue = 9,
                    BottomValue = 9,
                    LeftValue = 4,
                    Element = "thunder",
                    Level = 8,
                },
                new()
                {
                    Id = 12,
                    Name = "Gilgamesh",
                    Image = "gilgamesh.jpg",
                    TopValue = 3,
                    RightValue = 7,
                    BottomValue = 9,
                    LeftValue = 6,
                    Element = "none",
                    Level = 8,
                },
                new()
                {
                    Id = 13,
                    Name = "Angelo",
                    Image = "angelo.jpg",
                    TopValue = 9,
                    RightValue = 6,
                    BottomValue = 7,
                    LeftValue = 3,
                    Element = "none",
                    Level = 8,
                },
                new()
                {
                    Id = 32,
                    Name = "Elvoret",
                    Image = "elvoret.jpg",
                    TopValue = 7,
                    RightValue = 8,
                    BottomValue = 3,
                    LeftValue = 4,
                    Element = "wind",
                    Level = 6,
                },
                new()
                {
                    Id = 33,
                    Name = "X-ATM092",
                    Image = "x-atm092.jpg",
                    TopValue = 4,
                    RightValue = 8,
                    BottomValue = 7,
                    LeftValue = 3,
                    Element = "none",
                    Level = 6,
                },
                new()
                {
                    Id = 34,
                    Name = "Granaldo",
                    Image = "granaldo.jpg",
                    TopValue = 7,
                    RightValue = 2,
                    BottomValue = 8,
                    LeftValue = 5,
                    Element = "none",
                    Level = 6,
                },
                new()
                {
                    Id = 35,
                    Name = "Gerogero",
                    Image = "gerogero.jpg",
                    TopValue = 1,
                    RightValue = 8,
                    BottomValue = 8,
                    LeftValue = 3,
                    Element = "poison",
                    Level = 6,
                },
                new()
                {
                    Id = 36,
                    Name = "Iguion",
                    Image = "iguion.jpg",
                    TopValue = 8,
                    RightValue = 2,
                    BottomValue = 8,
                    LeftValue = 2,
                    Element = "none",
                    Level = 6,
                },
                new()
                {
                    Id = 37,
                    Name = "Abadon",
                    Image = "abadon.jpg",
                    TopValue = 6,
                    RightValue = 8,
                    BottomValue = 4,
                    LeftValue = 5,
                    Element = "none",
                    Level = 6,
                },
                new()
                {
                    Id = 38,
                    Name = "Trauma",
                    Image = "trauma.jpg",
                    TopValue = 4,
                    RightValue = 8,
                    BottomValue = 5,
                    LeftValue = 6,
                    Element = "none",
                    Level = 6,
                },
                new()
                {
                    Id = 39,
                    Name = "Oilboyle",
                    Image = "oilboyle.jpg",
                    TopValue = 1,
                    RightValue = 8,
                    BottomValue = 4,
                    LeftValue = 8,
                    Element = "none",
                    Level = 6,
                },
                new()
                {
                    Id = 40,
                    Name = "Shumi Tribe",
                    Image = "shumitribe.jpg",
                    TopValue = 6,
                    RightValue = 5,
                    BottomValue = 8,
                    LeftValue = 4,
                    Element = "none",
                    Level = 6,
                },
                new()
                {
                    Id = 41,
                    Name = "Krysta",
                    Image = "krysta.jpg",
                    TopValue = 7,
                    RightValue = 5,
                    BottomValue = 8,
                    LeftValue = 1,
                    Element = "none",
                    Level = 6,
                },
                new()
                {
                    Id = 42,
                    Name = "Propagator",
                    Image = "propogator.jpg",
                    TopValue = 8,
                    RightValue = 4,
                    BottomValue = 4,
                    LeftValue = 4,
                    Element = "none",
                    Level = 8,
                },
                new()
                {
                    Id = 43,
                    Name = "Jumbo Cactuar",
                    Image = "jumbocactuar.jpg",
                    TopValue = 8,
                    RightValue = 8,
                    BottomValue = 4,
                    LeftValue = 4,
                    Element = "none",
                    Level = 7,
                },
                new()
                {
                    Id = 44,
                    Name = "Tri-Point",
                    Image = "tri-point.jpg",
                    TopValue = 8,
                    RightValue = 5,
                    BottomValue = 2,
                    LeftValue = 8,
                    Element = "thunder",
                    Level = 7,
                },
                new()
                {
                    Id = 45,
                    Name = "Gargantua",
                    Image = "gargantua.jpg",
                    TopValue = 5,
                    RightValue = 6,
                    BottomValue = 6,
                    LeftValue = 8,
                    Element = "none",
                    Level = 7,
                },
                new()
                {
                    Id = 46,
                    Name = "Mobile Type 8",
                    Image = "mobiletype8.jpg",
                    TopValue = 8,
                    RightValue = 6,
                    BottomValue = 7,
                    LeftValue = 3,
                    Element = "none",
                    Level = 7,
                },
                new()
                {
                    Id = 47,
                    Name = "Sphinxara",
                    Image = "sphinxara.jpg",
                    TopValue = 8,
                    RightValue = 3,
                    BottomValue = 5,
                    LeftValue = 8,
                    Element = "none",
                    Level = 7,
                },
                new()
                {
                    Id = 48,
                    Name = "Tiamat",
                    Image = "tiamat.jpg",
                    TopValue = 8,
                    RightValue = 8,
                    BottomValue = 5,
                    LeftValue = 4,
                    Element = "none",
                    Level = 7,
                },
                new()
                {
                    Id = 49,
                    Name = "BGH251F2",
                    Image = "bgh251f2.jpg",
                    TopValue = 5,
                    RightValue = 7,
                    BottomValue = 8,
                    LeftValue = 5,
                    Element = "none",
                    Level = 7,
                },
                new()
                {
                    Id = 50,
                    Name = "Red Giant",
                    Image = "redgiant.jpg",
                    TopValue = 6,
                    RightValue = 8,
                    BottomValue = 4,
                    LeftValue = 7,
                    Element = "none",
                    Level = 7,
                },
                new()
                {
                    Id = 51,
                    Name = "Catoblepas",
                    Image = "catoblepas.jpg",
                    TopValue = 1,
                    RightValue = 8,
                    BottomValue = 7,
                    LeftValue = 7,
                    Element = "none",
                    Level = 7,
                },
                new()
                {
                    Id = 52,
                    Name = "Ultima Weapon",
                    Image = "ultimaweapon.jpg",
                    TopValue = 7,
                    RightValue = 7,
                    BottomValue = 2,
                    LeftValue = 8,
                    Element = "none",
                    Level = 7,
                },
                new()
                {
                    Id = 53,
                    Name = "Chubby Chocobo",
                    Image = "chubbychocobo.jpg",
                    TopValue = 4,
                    RightValue = 4,
                    BottomValue = 8,
                    LeftValue = 9,
                    Element = "none",
                    Level = 8,
                },
                new()
                {
                    Id = 54,
                    Name = "Angelo",
                    Image = "angelo.jpg",
                    TopValue = 9,
                    RightValue = 6,
                    BottomValue = 7,
                    LeftValue = 3,
                    Element = "none",
                    Level = 8,
                },
                new()
                {
                    Id = 55,
                    Name = "Wedge Biggs",
                    Image = "wedgebiggs.jpg",
                    TopValue = 6,
                    RightValue = 6,
                    BottomValue = 2,
                    LeftValue = 7,
                    Element = "none",
                    Level = 5,
                },
                // Level 7 Monster Cards
                new()
                {
                    Id = 56,
                    Name = "Behemoth",
                    Image = "behemoth.jpg",
                    TopValue = 3,
                    RightValue = 6,
                    BottomValue = 5,
                    LeftValue = 7,
                    Element = "none",
                    Level = 5,
                },
                new()
                {
                    Id = 57,
                    Name = "Chimera",
                    Image = "chimera.jpg",
                    TopValue = 7,
                    RightValue = 6,
                    BottomValue = 5,
                    LeftValue = 3,
                    Element = "water",
                    Level = 5,
                },
                new()
                {
                    Id = 58,
                    Name = "PuPu",
                    Image = "pupu.jpg",
                    TopValue = 3,
                    RightValue = 10,
                    BottomValue = 2,
                    LeftValue = 1,
                    Element = "none",
                    Level = 5,
                },
                new()
                {
                    Id = 59,
                    Name = "Elastoid",
                    Image = "elastoid.jpg",
                    TopValue = 6,
                    RightValue = 2,
                    BottomValue = 6,
                    LeftValue = 7,
                    Element = "none",
                    Level = 5,
                },
                new()
                {
                    Id = 60,
                    Name = "GIM47N",
                    Image = "gim47n.jpg",
                    TopValue = 5,
                    RightValue = 5,
                    BottomValue = 7,
                    LeftValue = 4,
                    Element = "none",
                    Level = 5,
                },
                new()
                {
                    Id = 61,
                    Name = "Malboro",
                    Image = "malboro.jpg",
                    TopValue = 7,
                    RightValue = 7,
                    BottomValue = 4,
                    LeftValue = 2,
                    Element = "poison",
                    Level = 5,
                },
                new()
                {
                    Id = 62,
                    Name = "Ruby Dragon",
                    Image = "rubydragon.jpg",
                    TopValue = 7,
                    RightValue = 2,
                    BottomValue = 7,
                    LeftValue = 4,
                    Element = "fire",
                    Level = 5,
                },
                new()
                {
                    Id = 63,
                    Name = "Elnoyle",
                    Image = "elnoyle.jpg",
                    TopValue = 5,
                    RightValue = 3,
                    BottomValue = 7,
                    LeftValue = 6,
                    Element = "none",
                    Level = 5,
                },
                new()
                {
                    Id = 64,
                    Name = "Tonberry King",
                    Image = "tonberryking.jpg",
                    TopValue = 4,
                    RightValue = 6,
                    BottomValue = 7,
                    LeftValue = 4,
                    Element = "none",
                    Level = 5,
                },
                // Level 6 Monster Cards
                new()
                {
                    Id = 31,
                    Name = "Fujin Raijin",
                    Image = "fujinraijin.jpg",
                    TopValue = 2,
                    RightValue = 8,
                    BottomValue = 8,
                    LeftValue = 4,
                    Element = "none",
                    Level = 6,
                },
                new()
                {
                    Id = 66,
                    Name = "Fastitocalon-F",
                    Image = "fastitocalon-f.jpg",
                    TopValue = 3,
                    RightValue = 5,
                    BottomValue = 2,
                    LeftValue = 1,
                    Element = "earth",
                    Level = 1,
                },
                new()
                {
                    Id = 67,
                    Name = "Snow Lion",
                    Image = "snowlion.jpg",
                    TopValue = 7,
                    RightValue = 1,
                    BottomValue = 5,
                    LeftValue = 3,
                    Element = "ice",
                    Level = 3,
                },
                new()
                {
                    Id = 68,
                    Name = "Ochu",
                    Image = "ochu.jpg",
                    TopValue = 5,
                    RightValue = 6,
                    BottomValue = 3,
                    LeftValue = 3,
                    Element = "none",
                    Level = 3,
                },
                new()
                {
                    Id = 69,
                    Name = "SAM08G",
                    Image = "sam08g.jpg",
                    TopValue = 5,
                    RightValue = 6,
                    BottomValue = 2,
                    LeftValue = 4,
                    Element = "fire",
                    Level = 3,
                },
                new()
                {
                    Id = 70,
                    Name = "Death Claw",
                    Image = "deathclaw.jpg",
                    TopValue = 4,
                    RightValue = 4,
                    BottomValue = 7,
                    LeftValue = 2,
                    Element = "fire",
                    Level = 6,
                },
                new()
                {
                    Id = 71,
                    Name = "Cactuar",
                    Image = "cactuar.jpg",
                    TopValue = 6,
                    RightValue = 2,
                    BottomValue = 6,
                    LeftValue = 3,
                    Element = "none",
                    Level = 3,
                },
                new()
                {
                    Id = 72,
                    Name = "Tonberry",
                    Image = "tonberry.jpg",
                    TopValue = 3,
                    RightValue = 6,
                    BottomValue = 4,
                    LeftValue = 4,
                    Element = "none",
                    Level = 3,
                },
                new()
                {
                    Id = 73,
                    Name = "Abyss Worm",
                    Image = "abyssworm.jpg",
                    TopValue = 7,
                    RightValue = 2,
                    BottomValue = 3,
                    LeftValue = 5,
                    Element = "earth",
                    Level = 3,
                },
                new()
                {
                    Id = 74,
                    Name = "Turtapod",
                    Image = "turtapod.jpg",
                    TopValue = 2,
                    RightValue = 3,
                    BottomValue = 6,
                    LeftValue = 7,
                    Element = "none",
                    Level = 4,
                },
                new()
                {
                    Id = 75,
                    Name = "Vysage",
                    Image = "vysage.jpg",
                    TopValue = 6,
                    RightValue = 5,
                    BottomValue = 4,
                    LeftValue = 5,
                    Element = "none",
                    Level = 4,
                },
                new()
                {
                    Id = 76,
                    Name = "T-Rexaur",
                    Image = "t-rexaur.jpg",
                    TopValue = 4,
                    RightValue = 6,
                    BottomValue = 2,
                    LeftValue = 7,
                    Element = "none",
                    Level = 4,
                },
                new()
                {
                    Id = 77,
                    Name = "Bomb",
                    Image = "bomb.jpg",
                    TopValue = 2,
                    RightValue = 7,
                    BottomValue = 6,
                    LeftValue = 3,
                    Element = "fire",
                    Level = 4,
                },
                new()
                {
                    Id = 78,
                    Name = "Blitz",
                    Image = "blitz.jpg",
                    TopValue = 1,
                    RightValue = 6,
                    BottomValue = 4,
                    LeftValue = 7,
                    Element = "thunder",
                    Level = 4,
                },
                new()
                {
                    Id = 79,
                    Name = "Wendigo",
                    Image = "wendigo.jpg",
                    TopValue = 7,
                    RightValue = 3,
                    BottomValue = 1,
                    LeftValue = 6,
                    Element = "none",
                    Level = 4,
                },
                new()
                {
                    Id = 80,
                    Name = "Torama",
                    Image = "torama.jpg",
                    TopValue = 7,
                    RightValue = 4,
                    BottomValue = 4,
                    LeftValue = 4,
                    Element = "none",
                    Level = 4,
                },
                new()
                {
                    Id = 81,
                    Name = "Imp",
                    Image = "imp.jpg",
                    TopValue = 3,
                    RightValue = 7,
                    BottomValue = 3,
                    LeftValue = 6,
                    Element = "none",
                    Level = 4,
                },
                new()
                {
                    Id = 82,
                    Name = "Blue Dragon",
                    Image = "bluedragon.jpg",
                    TopValue = 6,
                    RightValue = 2,
                    BottomValue = 7,
                    LeftValue = 3,
                    Element = "poison",
                    Level = 4,
                },
                new()
                {
                    Id = 83,
                    Name = "Adamantoise",
                    Image = "adamantoise.jpg",
                    TopValue = 4,
                    RightValue = 5,
                    BottomValue = 5,
                    LeftValue = 6,
                    Element = "earth",
                    Level = 4,
                },
                new()
                {
                    Id = 84,
                    Name = "Hexadragon",
                    Image = "hexadragon.jpg",
                    TopValue = 7,
                    RightValue = 5,
                    BottomValue = 4,
                    LeftValue = 3,
                    Element = "fire",
                    Level = 4,
                },
                // Level 5 Monster Cards
                new()
                {
                    Id = 85,
                    Name = "Iron Giant",
                    Image = "irongiant.jpg",
                    TopValue = 6,
                    RightValue = 5,
                    BottomValue = 6,
                    LeftValue = 5,
                    Element = "none",
                    Level = 5,
                },
                new()
                {
                    Id = 86,
                    Name = "Forbidden",
                    Image = "forbidden.jpg",
                    TopValue = 6,
                    RightValue = 6,
                    BottomValue = 3,
                    LeftValue = 2,
                    Element = "none",
                    Level = 5,
                },
                new()
                {
                    Id = 87,
                    Name = "Armadodo",
                    Image = "armadodo.jpg",
                    TopValue = 6,
                    RightValue = 3,
                    BottomValue = 1,
                    LeftValue = 6,
                    Element = "earth",
                    Level = 5,
                },
                new()
                {
                    Id = 88,
                    Name = "Tri-Face",
                    Image = "triface.jpg",
                    TopValue = 3,
                    RightValue = 5,
                    BottomValue = 5,
                    LeftValue = 5,
                    Element = "poison",
                    Level = 5,
                },
                new()
                {
                    Id = 89,
                    Name = "Fastitocalon",
                    Image = "fastitocalon.jpg",
                    TopValue = 7,
                    RightValue = 5,
                    BottomValue = 1,
                    LeftValue = 3,
                    Element = "earth",
                    Level = 5,
                },
                new()
                {
                    Id = 90,
                    Name = "Blood Soul",
                    Image = "bloodsoul.jpg",
                    TopValue = 2,
                    RightValue = 1,
                    BottomValue = 6,
                    LeftValue = 1,
                    Element = "none",
                    Level = 1,
                },
                new()
                {
                    Id = 91,
                    Name = "Caterchipillar",
                    Image = "caterchipillar.jpg",
                    TopValue = 4,
                    RightValue = 2,
                    BottomValue = 4,
                    LeftValue = 3,
                    Element = "none",
                    Level = 1,
                },
                new()
                {
                    Id = 92,
                    Name = "Cockatrice",
                    Image = "cockatrice.jpg",
                    TopValue = 2,
                    RightValue = 1,
                    BottomValue = 2,
                    LeftValue = 6,
                    Element = "thunder",
                    Level = 1,
                },
                // Level 4 and below Monster Cards
                new()
                {
                    Id = 93,
                    Name = "Grendel",
                    Image = "grendel.jpg",
                    TopValue = 4,
                    RightValue = 4,
                    BottomValue = 5,
                    LeftValue = 2,
                    Element = "thunder",
                    Level = 2,
                },
                new()
                {
                    Id = 94,
                    Name = "Jelleye",
                    Image = "jelleye.jpg",
                    TopValue = 3,
                    RightValue = 2,
                    BottomValue = 1,
                    LeftValue = 7,
                    Element = "none",
                    Level = 2,
                },
                new()
                {
                    Id = 95,
                    Name = "Grand Mantis",
                    Image = "grandmantis.jpg",
                    TopValue = 5,
                    RightValue = 2,
                    BottomValue = 5,
                    LeftValue = 3,
                    Element = "none",
                    Level = 2,
                },
                new()
                {
                    Id = 97,
                    Name = "Anacondaur",
                    Image = "anacondaur.jpg",
                    TopValue = 5,
                    RightValue = 1,
                    BottomValue = 3,
                    LeftValue = 5,
                    Element = "poison",
                    Level = 4,
                },
                new()
                {
                    Id = 98,
                    Name = "Creeps",
                    Image = "creeps.jpg",
                    TopValue = 5,
                    RightValue = 2,
                    BottomValue = 5,
                    LeftValue = 2,
                    Element = "thunder",
                    Level = 2,
                },
                new()
                {
                    Id = 99,
                    Name = "Grat",
                    Image = "grat.jpg",
                    TopValue = 7,
                    RightValue = 1,
                    BottomValue = 3,
                    LeftValue = 1,
                    Element = "none",
                    Level = 2,
                },
                new()
                {
                    Id = 100,
                    Name = "Buel",
                    Image = "buel.jpg",
                    TopValue = 6,
                    RightValue = 2,
                    BottomValue = 2,
                    LeftValue = 3,
                    Element = "none",
                    Level = 2,
                },
                new()
                {
                    Id = 101,
                    Name = "Mesmerize",
                    Image = "mesmerize.jpg",
                    TopValue = 5,
                    RightValue = 3,
                    BottomValue = 3,
                    LeftValue = 4,
                    Element = "none",
                    Level = 2,
                },
                new()
                {
                    Id = 102,
                    Name = "Glacial Eye",
                    Image = "glacialeye.jpg",
                    TopValue = 6,
                    RightValue = 1,
                    BottomValue = 4,
                    LeftValue = 3,
                    Element = "ice",
                    Level = 2,
                },
                new()
                {
                    Id = 103,
                    Name = "Belhelmel",
                    Image = "belhelmel.jpg",
                    TopValue = 3,
                    RightValue = 4,
                    BottomValue = 5,
                    LeftValue = 3,
                    Element = "none",
                    Level = 2,
                },
                new()
                {
                    Id = 104,
                    Name = "Thrustaevis",
                    Image = "thrustaevis.jpg",
                    TopValue = 5,
                    RightValue = 3,
                    BottomValue = 2,
                    LeftValue = 5,
                    Element = "wind",
                    Level = 2,
                },
                new()
                {
                    Id = 106,
                    Name = "Bite Bug",
                    Image = "bitebug.jpg",
                    TopValue = 1,
                    RightValue = 3,
                    BottomValue = 3,
                    LeftValue = 5,
                    Element = "none",
                    Level = 1,
                },
                new()
                {
                    Id = 107,
                    Name = "Red Bat",
                    Image = "redbat.jpg",
                    TopValue = 6,
                    RightValue = 1,
                    BottomValue = 1,
                    LeftValue = 2,
                    Element = "none",
                    Level = 1,
                },
                new()
                {
                    Id = 108,
                    Name = "Blobra",
                    Image = "blobra.jpg",
                    TopValue = 2,
                    RightValue = 3,
                    BottomValue = 1,
                    LeftValue = 5,
                    Element = "none",
                    Level = 1,
                },
                new()
                {
                    Id = 109,
                    Name = "Gayla",
                    Image = "gayla.jpg",
                    TopValue = 2,
                    RightValue = 1,
                    BottomValue = 4,
                    LeftValue = 4,
                    Element = "thunder",
                    Level = 1,
                },
                new()
                {
                    Id = 110,
                    Name = "Gesper",
                    Image = "gesper.jpg",
                    TopValue = 1,
                    RightValue = 5,
                    BottomValue = 4,
                    LeftValue = 1,
                    Element = "none",
                    Level = 1,
                },
                new()
                {
                    Id = 112,
                    Name = "Geezard",
                    Image = "geezard.jpg",
                    TopValue = 1,
                    RightValue = 4,
                    BottomValue = 1,
                    LeftValue = 5,
                    Element = "none",
                    Level = 1,
                },
                new()
                {
                    Id = 113,
                    Name = "Funguar",
                    Image = "funguar.jpg",
                    TopValue = 5,
                    RightValue = 1,
                    BottomValue = 1,
                    LeftValue = 3,
                    Element = "none",
                    Level = 1,
                },
                new()
                {
                    Id = 120,
                    Name = "MiniMog",
                    Image = "minimog.jpg",
                    TopValue = 9,
                    RightValue = 3,
                    BottomValue = 9,
                    LeftValue = 2,
                    Element = "none",
                    Level = 8,
                },
            };

            context.Cards.AddRange(cards);
            await context.SaveChangesAsync();
        }
    }
}
